package com.example.paycellwebclient.payment.refund;

import com.example.paycellwebclient.payment.model.RequestHeader;

public class RefundRequest {

    /**
     * Header information of the request
     */
    private RequestHeader requestHeader;

    /**
     * Merchant code: defined by Paycell Web SDK for each merchant
     */
    private String merchantCode;

    /**
     * Phone number of the customer
     * County code must be added
     */
    private String msisdn;

    /**
     * payment reference number of the payment that is subject to refund
     */
    private String originalReferenceNumber;

    /**
     * Uniqie id of the refund operation: generated by merchant
     */
    private String referenceNumber;

    /**
     * Amount of money that will be refunded. Last 2 digits represent cois.
     * 1.00 represented as "100"
     * 1.66 represented as "166"
     */
    private String amount;

    public RequestHeader getRequestHeader() {
        return requestHeader;
    }

    public void setRequestHeader(RequestHeader requestHeader) {
        this.requestHeader = requestHeader;
    }

    public String getMerchantCode() {
        return merchantCode;
    }

    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode;
    }

    public String getMsisdn() {
        return msisdn;
    }

    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }

    public String getOriginalReferenceNumber() {
        return originalReferenceNumber;
    }

    public void setOriginalReferenceNumber(String originalReferenceNumber) {
        this.originalReferenceNumber = originalReferenceNumber;
    }

    public String getReferenceNumber() {
        return referenceNumber;
    }

    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }
}
